using JevLauncher.Core;
using Xunit;

public class StoreAppsTests
{
    [Theory]
    [InlineData("Desinstalar Telegram", @"C:\Users\me\Telegram Desktop\unins000.exe", true)]
    [InlineData("Uninstall Node.js", "Microsoft.AutoGenerated.{6E69424D-6E5E}", true)]
    [InlineData("PostgreSQL documentation", "file://C:/doc/index.html", true)]
    [InlineData("User Manual", "https://manual.calibre-ebook.com/", true)]
    [InlineData("Release Notes", "VideoLAN.VLC", true)]
    [InlineData("Manual RAR para consola", @"{6D809377}\WinRAR\Rar.txt", true)]
    [InlineData("VLC media player", "VideoLAN.VLC", false)]
    [InlineData("Spotify", "SpotifyAB.SpotifyMusic_zpdnekdrzrea0!Spotify", false)]
    [InlineData("7-Zip", @"C:\Users\me\scoop\apps\7zip\current\7zFM.exe", false)]
    public void Noise_filter(string name, string path, bool expected)
    {
        Assert.Equal(expected, StoreApps.IsNoise(name, path));
    }

    [Fact]
    public void AppId_targets_the_apps_folder()
    {
        var candidate = StoreApps.ToCandidate(new StoreApp("Spotify", "SpotifyAB.SpotifyMusic_zpdnekdrzrea0!Spotify"));

        Assert.Equal(CandidateKind.OpenApp, candidate.Kind);
        Assert.Equal("Spotify", candidate.Title);
        Assert.Equal(@"shell:AppsFolder\SpotifyAB.SpotifyMusic_zpdnekdrzrea0!Spotify", candidate.Target);
    }

    [Fact]
    public void Absolute_path_targets_the_executable()
    {
        var candidate = StoreApps.ToCandidate(new StoreApp("7-Zip", @"C:\apps\7zFM.exe"));
        Assert.Equal(@"C:\apps\7zFM.exe", candidate.Target);
    }

    [Fact]
    public void Candidates_skip_titles_already_indexed()
    {
        var apps = new[]
        {
            new StoreApp("LOGI", "Chrome._crx_indjlapghbadokbidcmkjhgofd"),
            new StoreApp("Spotify", "SpotifyAB.SpotifyMusic_zpdnekdrzrea0!Spotify"),
        };

        var list = StoreApps.ToCandidates(apps, new[] { "LOGI" });

        Assert.Single(list);
        Assert.Equal("Spotify", list[0].Title);
    }

    [Fact]
    public void Enumerate_never_throws()
    {
        var apps = StoreApps.Enumerate();
        Assert.NotNull(apps);
    }
}
